all:
  children:
    hypervisor:
      hosts:
        localhost:
         ansible_connection: local
    masters:
      hosts:
        localhost:
         ansible_connection: local
    workers:
      hosts:
        localhost:
         ansible_connection: local
