all:
  vars:
    kube_controller_manager_cluster_cidr: 192.168.0.0/16
  children:
    hypervisor:
      hosts:
        localhost:
         ansible_connection: local
    masters:
      hosts:
        localhost:
         ansible_connection: local
    workers:
      hosts:
        localhost:
         ansible_connection: local
