all:
  vars:
    kube_controller_manager_cluster_cidr: 10.96.0.0/12
    admissionPlugins: 'NodeRestriction'
    protectKernelDefaults: false
  children:
    hypervisor:
      vars:
        nodes:
          - name: master-01
            template: ubuntu
          - name: master-02
            template: ubuntu
          - name: worker-01
            template: ubuntu
          - name: worker-02
            template: ubuntu
          - name: worker-03
            template: ubuntu
      hosts:
        localhost:
         ansible_connection: local
    masters:
      hosts:
        localhost:
    workers:
      hosts:
        localhost:
